# Generated by Django 6.0.6 on 2026-06-28 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kasir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SistemPembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='Sistem Pembayaran', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenyiapkanPesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('kasir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaran.kasir')),
            ],
        ),
        migrations.CreateModel(
            name='MengantarPesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('kasir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaran.kasir')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaran.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='MenerimaPesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaran.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='MelakukanPembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('kasir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaran.kasir')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaran.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='PesanMakananMinuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaran.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='PilihMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaran.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='ValidasiPembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('kasir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaran.kasir')),
                ('sistem_pembayaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaran.sistempembayaran')),
            ],
        ),
    ]
